# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "kt-paperclip"
env:
  RUBY_YJIT_ENABLE: 1
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ruby: [ 2.7.6 ]
        gemfile: [ 4.2 ]
#        ruby: [ 2.5, 2.6, 2.7, 3.0, 3.1, 3.2 ]
#        gemfile: [ 4.2, 5.0, 5.1, 5.2, 6.0, 6.1, 7.0 ]
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install gems
        uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cache-version: 1
      - name: Test
        run: bundle exec rake clean spec cucumber